/raid_data_collector:
  ros__parameters:
    navigation:
      action: "navigate_to_pose"
      path:
        topic: "/plan"
      status:
        topic: "/navigate_to_pose/_action/status"
    sensor:
      lidar:
        topic: "/scan"
        hi: 0
        hello: 0.0
      imu:
        topic: "/imu"
      gps:
        topic: "/sensor/gps/fix"
